aggr_type: mean
batch_size: 8
d1: 10
d2: 5
d3: 5
d4: 4
dataset: ./tmp/symbols_dataset_1_precomp_split_undersample_max_third/
epochs: 80
features: ''
learning_rate: 0.0001
model: GGNN5
num_classes: num_classes
num_layers: 2
weight_decay: 2e-4
