aggr_type: mean
batch_size: 16
d1: 30
d2: 10
dataset: ./tmp/symbols_dataset_1_precomp_split_undersample_max_half/
epochs: 100
features: ''
learning_rate: 0.01
model: GGNN1
num_classes: num_classes
num_layers: 2
weight_decay: 1e-4
