aggr_type: mean
batch_size: 32
d1: 40
d2: 20
d3: 10
d4: 10
d5: 5
dataset: ./tmp/symbols_dataset_1_precomp_split_undersample_max_third/
epochs: 200
features: ''
learning_rate: 0.01
model: GGNN6
num_classes: num_classes
num_layers: 2
weight_decay: 5e-4
