aggr_type: mean
batch_size: 16
d1: 10
d2: 5
d3: 4
d4: 4
dataset: ./tmp/symbols_dataset_3_precomp_split_undersample_max_half/
epochs: 20
features: ''
learning_rate: 0.01
model: GGNN5
num_classes: num_classes
num_layers: 4
weight_decay: 1e-4
